### ISSUE TITLE
MIDI note input

### ISSUE THREAD

**Issue by sonoro1234** [asb2m10/plugincollider#12]
Hello,

I have been able to use ControlBus parameters as a way to control synthdefs from plugin UI. It has been solved in a very general way for mapping 0-1 range to whatever the Synth needs. I like it because is minimal and ready to go for any situation (Althought I wouldn`t dislike a more customizable UI)

I have not been able to figure out how to get MIDI notes input from reaper to work with the plugin.
Can it be done?

Thanks
Victor Bombi

**Comment by asb2m10** [comment]
SupercolliderAU addressed this by sending OSC bundle [/midi /velocity] to scsynth instance: https://github.com/supercollider/SuperColliderAU/blob/main/Source/SCProcess.cpp#L108

I'm not to sure how it can be routed to the "default" node synthdef on the running instance of the server. Is it possible to help me on this ? At least have a synthdef instance that could cover this. Btw I'm on the Supercollider Discord server, feel free to PM me (asb2m10).

**Comment by sonoro1234** [comment]
> Is it possible to help me on this ?

By now I have only checked that: https://github.com/supercollider/SuperColliderAU/blob/f9bbd414a3462f2cc6ae4d1c1ac917aa1fc5666e/Source/SuperColliderAU.cpp#L184

If there is some PlugSpec? a synth is created on a fixed node (ID 1000) and then everything is sended to this synth. Seems quite limited and not polyphonic but I should do more investigation. Probably would be better to use it before, just to check what it does and what it does not, but I dont have an macosx system.

**Comment by sonoro1234** [comment]
The SuperColliderAU idea of ConfigSpec seems quite good for having fx that could be autonomous (no client needed).
The SynthDef could be saved with parameters definitions for UI controls (may be in a JSON file that can be made by the client previously: sclang or Lua2SC) and then loaded by PluginCollider and sent to World. (Althought the synthdef file just could be in a special location) I can help but all the VST part and settings should be guided by you. (I dont even know where settings are saved)

As for instruments the plan would be more complex. I would have a group with several Synths one for each note triggered. NoteOff should be managed also. It needs more thinking.

This is how it is basically done in Lua2SC: When you get a `noteon` you generate a new nodeid and you keep this nodeid in a table indexed by note.byte2, you send `/s_new` with this nodeid (I also convert note value to freq and velocity to amp for being able to use typical synthdefs). When a `noteoff` for this note.byte2 arrives you get the nodeid from the table and then send `/n_set` message to this node setting `gate` param to 0. If the synthdef has (as is typical in supercollider synthdefs) an EnvGen with gate and doneAction=2 (free-self when done) the Synth gently stops playing. This is the basic system where you can add sustain pedal, CC, mono playing, fx, etc

**Comment by sonoro1234** [comment]
If you could provide a mechanism for, at least, set the midi instrument synthdef name (empty name means no instrument) that can be setted independently in each PluginCollider instance, I could develop the process sketched above.

**Comment by asb2m10** [comment]
Thanks for the heads up. I think I know how to implement this.

**Comment by asb2m10** [comment]
Hi @sonoro1234 ,

Please check my implementation here: #18 

For now, the scsyndef is loaded from the plugin UI so I can save the blob into the plugin state so it can be reused afterwards. Also, the plugin can introspec the scsyndef parameters and expose them.

Next step would be to "catch/sniff" server message to save any scsyndef that is sent from sclang, but that will be implemented in another version.

For now the note playing works fine but I do see some "hang" notes even if the doneAction:2 is set.

Let me know how it works on your side.

**Comment by sonoro1234** [comment]
I have been able to compile. I am not able to find pluginPath or synthdefPath editor.
When playing midi `Syntdef not found: 1` is posted. I use Load button to choose a synthdef file (cheappiano.scsyndef for example) and then play midi but nothing is posted or sounds

**Comment by asb2m10** [comment]
The pluginPath is now in the server submenu and SC_DYNAMIC_PLUGINS must be set to show up.

I've just fixed your issue (please do a pull), I didn't check if there was an old invalid pluginState.

**Comment by sonoro1234** [comment]
Now I am able to load a synthdef and play!!
I still cant find synthPath variable editor
Also trying to understand audio routing for effects (got it: `NumOutputBuses.ir` is 2)

**Comment by sonoro1234** [comment]
> For now the note playing works fine but I do see some "hang" notes even if the doneAction:2 is set.

May be when note off arrives too quick? (In the same control period)

**Comment by sonoro1234** [comment]
> The pluginPath is now in the server submenu and SC_DYNAMIC_PLUGINS must be set to show up.

This is what I see compiling for SC_DYNAMIC_PLUGINS 

![Image](https://github.com/user-attachments/assets/89d8502c-1d19-4f3d-9ba2-6ddea5a69d05)

**Comment by asb2m10** [comment]
Hi @sonoro1234 , please check on develop, the SC_DYNAMIC_PLUGIN should be fixed for the menu and for now SC_SYNTHDEF_PATH should available from the menu.

**Comment by sonoro1234** [comment]
Working perfectly now!!

Some enhancement suggestions would be:

1- Hold notes with sustain pedal
2- Having an insert fx after note generation (for eq, reverb, soundboard) because it can be added to the instrument synthdefs but it is completely inefficient

**Comment by asb2m10** [comment]
Thanks for your feedback @sonoro1234 !

I'll transfer your enhancement to the discussion forum.
